"""init schema

Revision ID: 1a5d996a9aa2
Revises: 
Create Date: 2026-01-10 18:13:21.954356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a5d996a9aa2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('numero_documento', sa.String(length=20), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('sexo', sa.String(length=10), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_children_id'), 'children', ['id'], unique=False)
    op.create_index(op.f('ix_children_numero_documento'), 'children', ['numero_documento'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('numero_documento', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_numero_documento'), 'users', ['numero_documento'], unique=True)
    op.create_index(op.f('ix_users_rol'), 'users', ['rol'], unique=False)
    op.create_table('vaccines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaccines_id'), 'vaccines', ['id'], unique=False)
    op.create_index(op.f('ix_vaccines_nombre'), 'vaccines', ['nombre'], unique=True)
    op.create_table('parent_child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('parentesco', sa.String(length=30), nullable=False),
    sa.Column('es_principal', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'child_id', name='uq_parent_child')
    )
    op.create_index(op.f('ix_parent_child_child_id'), 'parent_child', ['child_id'], unique=False)
    op.create_index(op.f('ix_parent_child_id'), 'parent_child', ['id'], unique=False)
    op.create_index(op.f('ix_parent_child_parent_id'), 'parent_child', ['parent_id'], unique=False)
    op.create_table('vaccine_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vaccine_id', sa.Integer(), nullable=False),
    sa.Column('dosis_numero', sa.Integer(), nullable=False),
    sa.Column('edad_objetivo_meses', sa.Integer(), nullable=False),
    sa.Column('intervalo_min_dias', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vaccine_id'], ['vaccines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vaccine_id', 'dosis_numero', name='uq_vaccine_dose')
    )
    op.create_index(op.f('ix_vaccine_schedule_id'), 'vaccine_schedule', ['id'], unique=False)
    op.create_index(op.f('ix_vaccine_schedule_vaccine_id'), 'vaccine_schedule', ['vaccine_id'], unique=False)
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('pediatrician_id', sa.Integer(), nullable=False),
    sa.Column('fecha_atencion', sa.Date(), nullable=False),
    sa.Column('peso_kg', sa.Float(), nullable=False),
    sa.Column('talla_cm', sa.Float(), nullable=False),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pediatrician_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_child_id'), 'visits', ['child_id'], unique=False)
    op.create_index(op.f('ix_visits_id'), 'visits', ['id'], unique=False)
    op.create_index(op.f('ix_visits_pediatrician_id'), 'visits', ['pediatrician_id'], unique=False)
    op.create_table('vaccine_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('fecha_aplicacion', sa.Date(), nullable=False),
    sa.Column('lote', sa.String(length=50), nullable=True),
    sa.Column('proxima_fecha', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['schedule_id'], ['vaccine_schedule.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', 'schedule_id', name='uq_child_schedule_once')
    )
    op.create_index(op.f('ix_vaccine_applications_child_id'), 'vaccine_applications', ['child_id'], unique=False)
    op.create_index(op.f('ix_vaccine_applications_id'), 'vaccine_applications', ['id'], unique=False)
    op.create_index(op.f('ix_vaccine_applications_schedule_id'), 'vaccine_applications', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_vaccine_applications_visit_id'), 'vaccine_applications', ['visit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vaccine_applications_visit_id'), table_name='vaccine_applications')
    op.drop_index(op.f('ix_vaccine_applications_schedule_id'), table_name='vaccine_applications')
    op.drop_index(op.f('ix_vaccine_applications_id'), table_name='vaccine_applications')
    op.drop_index(op.f('ix_vaccine_applications_child_id'), table_name='vaccine_applications')
    op.drop_table('vaccine_applications')
    op.drop_index(op.f('ix_visits_pediatrician_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_child_id'), table_name='visits')
    op.drop_table('visits')
    op.drop_index(op.f('ix_vaccine_schedule_vaccine_id'), table_name='vaccine_schedule')
    op.drop_index(op.f('ix_vaccine_schedule_id'), table_name='vaccine_schedule')
    op.drop_table('vaccine_schedule')
    op.drop_index(op.f('ix_parent_child_parent_id'), table_name='parent_child')
    op.drop_index(op.f('ix_parent_child_id'), table_name='parent_child')
    op.drop_index(op.f('ix_parent_child_child_id'), table_name='parent_child')
    op.drop_table('parent_child')
    op.drop_index(op.f('ix_vaccines_nombre'), table_name='vaccines')
    op.drop_index(op.f('ix_vaccines_id'), table_name='vaccines')
    op.drop_table('vaccines')
    op.drop_index(op.f('ix_users_rol'), table_name='users')
    op.drop_index(op.f('ix_users_numero_documento'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_children_numero_documento'), table_name='children')
    op.drop_index(op.f('ix_children_id'), table_name='children')
    op.drop_table('children')
    # ### end Alembic commands ###
