"""add created_by to parent_child

Revision ID: 20a7d6a55a7a
Revises: 86b84c73b042
Create Date: 2026-01-10 18:57:11.392946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20a7d6a55a7a'
down_revision: Union[str, Sequence[str], None] = '86b84c73b042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_child', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_parent_child_created_by'), 'parent_child', ['created_by'], unique=False)
    op.create_foreign_key(None, 'parent_child', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parent_child', type_='foreignkey')
    op.drop_index(op.f('ix_parent_child_created_by'), table_name='parent_child')
    op.drop_column('parent_child', 'created_by')
    # ### end Alembic commands ###
