"""add created_by to users

Revision ID: 30550200ce31
Revises: 1a5d996a9aa2
Create Date: 2026-01-10 18:19:27.502582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30550200ce31'
down_revision: Union[str, Sequence[str], None] = '1a5d996a9aa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_created_by'), 'users', ['created_by'], unique=False)
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_created_by'), table_name='users')
    op.drop_column('users', 'created_by')
    # ### end Alembic commands ###
