"""add vaccination tables

Revision ID: 765f6312d1e4
Revises: 
Create Date: 2025-11-16 22:53:43.548381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '765f6312d1e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargos_medicos',
    sa.Column('id_cargo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('id_usuario_creo', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_cargo')
    )
    op.create_index(op.f('ix_cargos_medicos_id_cargo'), 'cargos_medicos', ['id_cargo'], unique=False)
    op.create_table('centro_salud',
    sa.Column('id_centro', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('responsable', sa.String(length=100), nullable=True),
    sa.Column('nivel', sa.String(length=50), nullable=True),
    sa.Column('horario_atencion', sa.String(length=100), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('id_usuario_creo', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_centro')
    )
    op.create_index(op.f('ix_centro_salud_id_centro'), 'centro_salud', ['id_centro'], unique=False)
    op.create_table('personas',
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('numero_documento', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_persona')
    )
    op.create_index(op.f('ix_personas_id_persona'), 'personas', ['id_persona'], unique=False)
    op.create_index(op.f('ix_personas_numero_documento'), 'personas', ['numero_documento'], unique=True)
    op.create_table('tipos_vacunas',
    sa.Column('id_vacuna', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('edad_recomendada', sa.String(length=50), nullable=True),
    sa.Column('dosis_requeridas', sa.Integer(), nullable=True),
    sa.Column('id_usuario_creo', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_vacuna')
    )
    op.create_index(op.f('ix_tipos_vacunas_id_vacuna'), 'tipos_vacunas', ['id_vacuna'], unique=False)
    op.create_table('historial_vacunacion',
    sa.Column('id_historial', sa.Integer(), nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('id_centro', sa.Integer(), nullable=False),
    sa.Column('id_cargo', sa.Integer(), nullable=False),
    sa.Column('fecha_aplicacion', sa.Date(), nullable=False),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('id_usuario_creo', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_cargo'], ['cargos_medicos.id_cargo'], ),
    sa.ForeignKeyConstraint(['id_centro'], ['centro_salud.id_centro'], ),
    sa.ForeignKeyConstraint(['id_persona'], ['personas.id_persona'], ),
    sa.PrimaryKeyConstraint('id_historial')
    )
    op.create_index(op.f('ix_historial_vacunacion_id_historial'), 'historial_vacunacion', ['id_historial'], unique=False)
    op.create_table('relacion_padre_hijo',
    sa.Column('id_relacion', sa.Integer(), nullable=False),
    sa.Column('id_padre', sa.Integer(), nullable=False),
    sa.Column('id_hijo', sa.Integer(), nullable=False),
    sa.Column('tipo_relacion', sa.String(length=50), nullable=True),
    sa.Column('id_usuario_creo', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_hijo'], ['personas.id_persona'], ),
    sa.ForeignKeyConstraint(['id_padre'], ['personas.id_persona'], ),
    sa.PrimaryKeyConstraint('id_relacion')
    )
    op.create_index(op.f('ix_relacion_padre_hijo_id_relacion'), 'relacion_padre_hijo', ['id_relacion'], unique=False)
    op.create_table('detalle_historial_vacuna',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_historial', sa.Integer(), nullable=False),
    sa.Column('id_vacuna', sa.Integer(), nullable=False),
    sa.Column('lote', sa.String(length=50), nullable=True),
    sa.Column('dosis_numero', sa.Integer(), nullable=True),
    sa.Column('fecha_proxima', sa.Date(), nullable=True),
    sa.Column('id_usuario_creo', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_historial'], ['historial_vacunacion.id_historial'], ),
    sa.ForeignKeyConstraint(['id_vacuna'], ['tipos_vacunas.id_vacuna'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_index(op.f('ix_detalle_historial_vacuna_id_detalle'), 'detalle_historial_vacuna', ['id_detalle'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalle_historial_vacuna_id_detalle'), table_name='detalle_historial_vacuna')
    op.drop_table('detalle_historial_vacuna')
    op.drop_index(op.f('ix_relacion_padre_hijo_id_relacion'), table_name='relacion_padre_hijo')
    op.drop_table('relacion_padre_hijo')
    op.drop_index(op.f('ix_historial_vacunacion_id_historial'), table_name='historial_vacunacion')
    op.drop_table('historial_vacunacion')
    op.drop_index(op.f('ix_tipos_vacunas_id_vacuna'), table_name='tipos_vacunas')
    op.drop_table('tipos_vacunas')
    op.drop_index(op.f('ix_personas_numero_documento'), table_name='personas')
    op.drop_index(op.f('ix_personas_id_persona'), table_name='personas')
    op.drop_table('personas')
    op.drop_index(op.f('ix_centro_salud_id_centro'), table_name='centro_salud')
    op.drop_table('centro_salud')
    op.drop_index(op.f('ix_cargos_medicos_id_cargo'), table_name='cargos_medicos')
    op.drop_table('cargos_medicos')
    # ### end Alembic commands ###
