"""vaccines visits applications

Revision ID: 845a9bfbbfa4
Revises: 20a7d6a55a7a
Create Date: 2026-01-10 19:03:08.477067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '845a9bfbbfa4'
down_revision: Union[str, Sequence[str], None] = '20a7d6a55a7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
